# Permalinks
permalink:        pretty

# Setup
title:            Payload
tagline:          'The Blog'
description:      'The official <a href="https://payload.pk" target="_blank">Payload</a> blog.'
url:              //blog.payload.pk
baseurl:          /

authors:
  gilani:
    name:           'Amin Shah Gilani'
    url:            https://twitter.com/amingilani
  sulaiman:
    name:           'Sulaiman Khan'
    url:            https://twitter.com/sulykhan
  zakra:
    name:           'Zakra Chachar'
    url:            https://twitter.com/zakrachachar

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/payloadpk/blog
